pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'mallikarjun7/python-app:v1'
        }

    stages {
        stage('Docker login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'mallikarjun7', passwordVariable: 'DockerPassword', usernameVariable: 'DockerUsername')]) {
                    sh 'docker login -u ${DockerUsername} -p ${DockerPassword}'
                    echo "successfully logged into docker"
                }
            }
        }        
        stage('Docker image pull') {
            steps {
                sh 'docker pull ${DOCKER_IMAGE}'
                echo "successfully pulled image ${DOCKER_IMAGE}"
                                }
                        }
                    }
            }